repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: forbid-new-submodules
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.152
    hooks:
      - id: ruff
        files: ^api/

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: ^api/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.6.0'
    hooks:
      - id: prettier
        args: ['--write']
        files: ^web/
