version: "3.7"

services:
  postgres:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - ./api/scripts/wait-for-postgres.sh:/home/wait-for-postgres.sh
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonarbook
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: sonarbook
        POSTGRES_PORT: 5432
    env_file:
      - api/.env.development

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000


volumes:
  db-data:
